### ISSUE TITLE
MAQs is display wrong result

### ISSUE THREAD

**Issue by tonquangkhai** [AbdulBasit313/React-Quiz-App-Template#1]
Please ensure that you review the logic for evaluating the results of the MAQs (Multiple Answer Questions). In the current implementation, if a user selects the correct answers but in a different order than the correctAnswers array, the result will be marked as incorrect. This is because the existing code checks for the exact order of answers.

- Original code:
```
const isMatch: boolean = correctAnswers.every(
  (answer: string, index: number) => answer === selectedAnswer[index]
);
```

The above code only checks if each answer in the correctAnswers array matches exactly with the answer at the same index in the selectedAnswer array. This means the order matters.

- Recommended correction:
To fix this issue, first, check if the length of the selectedAnswer and correctAnswers arrays are the same. Then, ensure that every answer in the selectedAnswer array exists within the correctAnswers array regardless of the order.

```
const isMatch: boolean = selectedAnswer.length === correctAnswers.length &&
  selectedAnswer.every(answer => correctAnswers.includes(answer));
```
This approach ensures that the user gets the correct result even if they select the right answers in a different order than the correctAnswers array."

**Comment by tonquangkhai** [comment]
![Screenshot 2023-09-03 at 2 17 49 AM](https://github.com/AbdulBasit313/React-Quiz-App-Template/assets/25828463/a8edd200-cdf5-49da-bc68-b5e797bcdfee)
Another issue is that our code exposes all data in the bundle file. Can we implement an encryption solution to safeguard this data, ensuring that web crawlers can't easily access it?

**Comment by AbdulBasit313** [comment]
fixed

**Comment by AbdulBasit313** [comment]
> ![Screenshot 2023-09-03 at 2 17 49 AM](https://user-images.githubusercontent.com/25828463/265225152-a8edd200-cdf5-49da-bc68-b5e797bcdfee.png) Another issue is that our code exposes all data in the bundle file. Can we implement an encryption solution to safeguard this data, ensuring that web crawlers can't easily access it?

This can only be hidden to some extent.

**Comment by AbdulBasit313** [comment]
> Please ensure that you review the logic for evaluating the results of the MAQs (Multiple Answer Questions). In the current implementation, if a user selects the correct answers but in a different order than the correctAnswers array, the result will be marked as incorrect. This is because the existing code checks for the exact order of answers.
> 
> * Original code:
> 
> ```
> const isMatch: boolean = correctAnswers.every(
>   (answer: string, index: number) => answer === selectedAnswer[index]
> );
> ```
> 
> The above code only checks if each answer in the correctAnswers array matches exactly with the answer at the same index in the selectedAnswer array. This means the order matters.
> 
> * Recommended correction:
>   To fix this issue, first, check if the length of the selectedAnswer and correctAnswers arrays are the same. Then, ensure that every answer in the selectedAnswer array exists within the correctAnswers array regardless of the order.
> 
> ```
> const isMatch: boolean = selectedAnswer.length === correctAnswers.length &&
>   selectedAnswer.every(answer => correctAnswers.includes(answer));
> ```
> 
> This approach ensures that the user gets the correct result even if they select the right answers in a different order than the correctAnswers array."

fixed

**Comment by tonquangkhai** [comment]
Great. Thank you for your quick response.
